name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.devUsername }}
      MYSQL_PASSWORD: ${{ secrets.devPassword }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.devPassword }}
      MYSQL_DATABASE: ${{ secrets.devDB }}
    ports:
     - 3306:3306
    options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Display environment variables
        run: |
          echo devUsername=${{ secrets.devUsername }}
          echo devPassword=${{ secrets.devPassword }}
          echo devDB=${{ secrets.devDB }}
          echo devHost=${{ secrets.devHost }}
          echo PORT=${{ secrets.PORT }}

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -e "CREATE DATABASE $MYSQL_DATABASE;"
          

      - name: Run Tests
        run: |
          npx mocha test/user.test.js
