name: Continuous Integration Test Workflow
 
on:
  pull_request:
    branches:
        - main
 
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install

    - name: Display .env file
      run: |

        echo "DEVUSERNAME = ${{secrets.DEVUSERNAME}}" >> .env

        echo "DEVPASSWORD = ${{secrets.DEVPASSWORD}}" >> .env

        echo "DEVDB = ${{secrets.DEVDB}}" >> .env

        echo "PORT=${{secrets.PORT}}" >> .env
        echo "DEVHOST=${{secrets.DEVHOST}}" >> .env

        cat .env

       

    - name: configuremysql

      run: |

        sudo apt-get update

        sudo apt-get install -y curl

        sudo systemctl start mysql

        sudo systemctl status mysql

        mysql -u root -p"root" -e "CREATE DATABASE  database_development;"

        sudo mysql -e "GRANT ALL ON *.* TO '${{secrets.DEVUSERNAME}}'@'localhost' IDENTIFIED BY '${{secrets.DEVPASSWORD}}';"

        sudo mysql -e "FLUSH PRIVILEGES;"

        

 

  #  asd

 

    - name: Run Tests
      run : |
        npx mocha test/user.test.js
