name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      devUsername: ${{ secrets.MYSQL_USER }}
      devPassword: ${{ secrets.MYSQL_PASSWORD }}
      devDb: ${{ secrets.MYSQL_DATABASE }}
      devHost: ${{ secrets.MYSQL_HOST }}
      
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display environment variables
        run: |
          echo "devUsername = $MYSQL_USER" >> .env
          echo "devPassword = $MYSQL_PASSWORD" >> .env
          echo "devDB = $MYSQL_DATABASE" >> .env
          echo "devHost: ${{ secrets.MYSQL_HOST }}" >>.env"
          cat .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          
          # Print MySQL status and try connecting with the root user
          echo "Trying to connect to MySQL with root user"
          mysql -u root -e "SHOW DATABASES;"
          
          # Create a new user and grant privileges for testing
          sudo mysql -u root -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';"
          sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'localhost';"
          sudo mysql -u root -e "FLUSH PRIVILEGES;"
          
          # Create the database using the new user
          mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
          mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -e "SHOW DATABASES;"

      - name: Run Tests
        run: |
          npx mocha test/user.test.js
