name: Continuous Integration Test Workflow
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      DEVUSERNAME: ${{ secrets.DEVUSERNAME }}
      DEVPASSWORD: ${{ secrets.DEVPASSWORD }}
      DEVDB: ${{ secrets.DEVDB }}
      DEVHOST: ${{ secrets.DEVHOST }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}  # Adding the root password environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display .env file
        run: |
          echo "DEVUSERNAME = $DEVUSERNAME" >> .env
          echo "DEVPASSWORD = $DEVPASSWORD" >> .env
          echo "DEVDB = $DEVDB" >> .env
          echo "PORT = $PORT" >> .env
          echo "DEVHOST = $DEVHOST" >> .env
          cat .env

      - name: Install and Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

          # Start MySQL service
          sudo systemctl start mysql

          # Check the status of MySQL service
          sudo systemctl status mysql

          # Set up root user with password and create a new user and database
          echo "Setting up MySQL root user and creating database"
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_ROOT_PASSWORD';"
          sudo mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DEVDB;"
          sudo mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER IF NOT EXISTS '$DEVUSERNAME'@'localhost' IDENTIFIED BY '$DEVPASSWORD';"
          sudo mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON *.* TO '$DEVUSERNAME'@'localhost';"
          sudo mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"

      - name: Run Tests
        run: |
          npx mocha test/user.test.js
