name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      PORT: ${{ secrets.PORT }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display environment variables
        run: |
          echo "MYSQL_USER = $MYSQL_USER" >> .env
          echo "MYSQL_PASSWORD = $MYSQL_PASSWORD" >> .env
          echo "MYSQL_DATABASE = $MYSQL_DATABASE" >> .env
          echo "PORT = $PORT" >> .env
          cat .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -e "CREATE DATABASE $MYSQL_DATABASE;"

      - name: Run Tests
        run: |
          npx mocha test/user.test.js
