name: Continuous Integration Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      DEVUSERNAME:  "root" 
      DEVPASSWORD: "root"
      DEVDB: ${{ secrets.DEVPDB }}
      DEVHOST: ${{ secrets.DEVHOST }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Display .env file
      run: |
        touch .env
        echo DEVUSERNAME="${{ env.DEVUSERNAME }}" >> .env
        echo DEVPASSWORD="${{ env.DEVPASSWORD }}" >> .env
        echo DEVDB="${{ env.DEVDB }}" >> .env
        echo PORT="${{ secrets.PORT }}" >> .env
        echo DEVHOST="${{ env.DEVHOST }}" >> .env
        cat .env

    - name: Start and configure MySQL
      run: |
      
        sudo systemctl start mysql

        
        sudo systemctl status mysql

        
        sudo mysql --user=root --password="${{ env.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS \`${{ env.DEVDB }}\`;"
        sudo mysql --user=root --password="${{ env.MYSQL_ROOT_PASSWORD }}" -e "CREATE USER IF NOT EXISTS '${{ env.DEVUSERNAME }}'@'localhost' IDENTIFIED BY '${{ env.DEVPASSWORD }}';"
        sudo mysql --user=root --password="${{ env.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON \`${{ env.DEVDB }}\`.* TO '${{ env.DEVUSERNAME }}'@'localhost';"
        sudo mysql --user=root --password="${{ env.MYSQL_ROOT_PASSWORD }}" -e "FLUSH PRIVILEGES;"

    - name: Run Tests
      run: |
        # Run your tests using Mocha
        npx mocha --exit --timeout 10000 test/user.test.js
