name: Continuous Integration Test Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      DEVUSERNAME:  "root" 
      DEVPASSWORD: "root"
      DEVDB: ${{ secrets.DEVPDB }}
      DEVHOST: ${{ secrets.DEVHOST }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    

    - name: Run Tests
      run: |
        # Run your tests using Mocha
        npm test
