name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      devUsername: ${{ secrets.MYSQL_USER }}
      devPassword: ${{ secrets.MYSQL_PASSWORD }}
      devDB: ${{ secrets.MYSQL_DATABASE }}
      devHost: ${{ secrets.MYSQL_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display environment variables
        run: |
          echo "devUsername = $devUsername" >> .env
          echo "devPassword = $devPassword" >> .env
          echo "devDB = $devDB" >> .env
          echo "devHost = $devHost" >> .env  # Corrected the format here
          cat .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql

          # Print MySQL status and try connecting with the root user
          echo "Trying to connect to MySQL with root user"
          sudo mysql -e "SHOW DATABASES;"

          # Temporarily set a root password and change the authentication method if needed
          echo "Setting root password and changing authentication method"
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"

          # Create a new MySQL user with the given credentials and database
          sudo mysql -u root -proot -e "CREATE USER IF NOT EXISTS '$devUsername'@'localhost' IDENTIFIED BY '$devPassword';"
          sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO '$devUsername'@'localhost';"
          sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS $devDB;"
          sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"

          # Verify connection using the new user and list databases
          mysql -u $devUsername -p"$devPassword" -e "SHOW DATABASES;"

      - name: Run Tests
        run: |
          npx mocha test/user.test.js
